/**
 * HYBRID DISCORD COMMAND CENTER
 * Reads static fallback data for offline staff, and live widget data for online status.
 */

const SERVER_ID = '1433645535583277129';
const SILHOUETTE = 'https://archive.org/download/discord_default_avatars/gray.png';

async function syncSystem() {
    console.log(">> Initiating System Sync...");
    try {
        // 1. Fetch the Live Discord Widget (for orbit and glowing online status)
        const widgetResponse = await fetch(`https://discord.com/api/guilds/${SERVER_ID}/widget.json`);
        const widgetData = await widgetResponse.json();
        const onlineList = widgetData.members;
        
        // Update total online count
        document.getElementById('active-count').innerText = 
            widgetData.presence_count < 10 ? `0${widgetData.presence_count}` : widgetData.presence_count;

        // 2. Fetch your Offline Database (generated by GitHub Actions)
        let staffDatabase = [];
        try {
            const dbResponse = await fetch('./staff_data.json');
            staffDatabase = await dbResponse.json();
        } catch (e) {
            console.warn(">> staff_data.json not found yet. The GitHub Action might still be running.");
        }

        // 3. Process the Hierarchy Grid
        const nodes = document.querySelectorAll('.node-container');
        const staffIds = []; // Keep track of staff so we don't put them in the orbit ring

        nodes.forEach(node => {
            const uid = node.getAttribute('data-id');
            staffIds.push(uid);
            
            const pfpEl = node.querySelector('.node-pfp');
            const nameEl = node.querySelector('.username');

            // Check if they are in the live widget (Online)
            const liveMember = onlineList.find(m => m.id === uid);
            // Check if we have their archived info (Offline fallback)
            const archivedMember = staffDatabase.find(m => m.id === uid);

            if (liveMember) {
                // ONLINE: Glow effect and live data
                node.classList.add('online');
                if (pfpEl) pfpEl.style.backgroundImage = `url('${liveMember.avatar_url}')`;
                if (nameEl) nameEl.innerText = liveMember.username.toUpperCase();
            } else if (archivedMember) {
                // OFFLINE: Dim effect, but still show their picture from the database
                node.classList.remove('online');
                if (pfpEl) pfpEl.style.backgroundImage = `url('${archivedMember.avatar}')`;
                if (nameEl) nameEl.innerText = `${archivedMember.name.toUpperCase()} [OFF]`;
            } else {
                // NO DATA: Fallback if the bot hasn't fetched them yet
                node.classList.remove('online');
                if (pfpEl) pfpEl.style.backgroundImage = `url('${SILHOUETTE}')`;
                if (nameEl) nameEl.innerText = "NO DATA";
            }
        });

        // 4. Process the Orbit Ring (Only non-staff online members)
        const orbitField = document.getElementById('member-orbit-field');
        orbitField.innerHTML = '';
        
        const civilianMembers = onlineList.filter(m => !staffIds.includes(m.id));
        const maxOrbit = 15; 
        
        civilianMembers.slice(0, maxOrbit).forEach((m, i) => {
            const angle = (i / Math.min(civilianMembers.length, maxOrbit)) * (Math.PI * 2);
            const radius = 120;
            const x = Math.cos(angle) * radius + 150 - 17;
            const y = Math.sin(angle) * radius + 150 - 17;

            const div = document.createElement('div');
            div.className = 'orbit-node';
            div.style.left = `${x}px`;
            div.style.top = `${y}px`;
            div.style.backgroundImage = `url('${m.avatar_url}')`;
            div.style.backgroundSize = 'cover';
            div.title = m.username;

            orbitField.appendChild(div);
        });

        document.getElementById('signal-status').innerText = "ESTABLISHED";
        document.getElementById('signal-status').className = "value pulse-green";

    } catch (err) {
        console.error(">> Critical System Error:", err);
        document.getElementById('signal-status').innerText = "LINK_LOST";
        document.getElementById('signal-status').className = "value pulse-red";
    }
}

// System Boot
document.addEventListener('DOMContentLoaded', () => {
    syncSystem();
    // Re-sync every 45 seconds to keep the orbit ring alive
    setInterval(syncSystem, 45000);
});
